# Generated by Django 4.2.3 on 2023-07-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('dept', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
    ]
